NetworkingInitCmsBundle:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing.yml"
    prefix:   /
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translation