SandboxInitCmsBundle:
    resource: "@SandboxInitCmsBundle/Controller/WelcomeController.php"
    type:     annotation
    prefix:   /

NetworkingInitCmsBundle:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing.yml"
    prefix:   /
