sandbox_init_cms:
    resource: "@SandboxInitCmsBundle/Controller/"
    type:     annotation
    prefix:   /

NetworkingInitCmsBundle:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing.yml"
    prefix:   /